# Generated by Django 5.2 on 2025-07-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_marker_msisdn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='msisdn',
        ),
    ]
